### PR TITLE
faster and simpler ancestors generation

### PR DESCRIPTION
**Pull request by ezpuzz**
hi @Einenlum !  Thanks for the great plugin, it makes working with docker-compose yml files a breeze!

I looked in to your code because I noticed a few bugs and saw that it could be implemented more simply with a recursive function.  😄 

It works more reliably and is faster I think!  Let me know your thoughts.

Thanks,
e

### CODE REVIEW

**Comment by ezpuzz** [comment]
oh I may have removed your default maps, it's mostly not good form to clobber the global maps like that.

You may have noticed I also moved the main vim file to a ftplugin so it only loads on yaml files.  This has the added benefit of working with compound filetypes.  The docker vim plugin I use reads docker-compose files as the filetype `yaml.docker-compose` which did not load with your plugin.  By using a ftplugin the code is loaded for the filetype correctly.

**Comment by Einenlum** [comment]
Hi @ezpuzz ! Thank you so much for your work!
I just have a question: it seems the echoed line has changed.

```yaml
services:
    php:
        build: './docker/php'
```
Being on the `build` line will echo `services > php` while before it was `services > php > build`.
Was it changed on purpose?
I'm not sure what behavior is the best (maybe the new one is better cause sometimes there is no key like when we are in an array), but if we keep this new behavior I think it would be nice to update the readme example. At least the code example (I can make another gif later to update it) :)

**Comment by Einenlum** [comment]
@ezpuzz Also, I can't create a new yaml file with your pluggin. It works with existant files but not with new files I create. I get a syntax error:

```
Error in function GetAncestors[6]..GetAncestors :                                                                                                      
line   12 :                                                                                                                                                              
E554: Syntax error in \{...}                  
```

**Comment by ezpuzz** [comment]
Woah, didn't catch that.  I'll fix it up.

**Comment by ezpuzz** [comment]
hey @Einenlum know it's been a while but i've been using my fork the past few months.  this latest push should update readme, fix behavior with empty file, and sets autogroup in a more correct way.

**Comment by Einenlum** [comment]
I missed this! Sorry for the late merge. Thanks for your work @ezpuzz !

**Pull request merged**
